In [ ]:
# This is the code for cleaning the NBA data
#The clean data is returned in the file "NBA_clean.csv"

In [1]:
import os
import csv
import datetime
import pandas as pd
import numpy as np

In [2]:
#====================================================================================================
#=======================Building Dataset for yearly salaries with Player name as Key=================
#====================================================================================================
historic_bball = os.path.join("nba_salaries_1990_to_2018.csv")

# Set empty list variables
Player= []
Salary = []
Season = []

  #Open current NBA CSV to zip important Values into a df
with open(historic_bball, 'r') as csvFile:                    

   csvReader = csv.reader(csvFile, delimiter=',')

   # Skipp headers
   next(csvReader, None)                                      

   for row in csvReader:

       # Append data from the row
       Player.append(row[0])
       Salary.append(row[1])
       Season.append(row[2])
    
# Zip lists together
cleanCSV = list(zip(Player, Salary, Season))
#cleanCSV                        #Returns raw data for processing into dataframe

In [3]:
df = pd.DataFrame(cleanCSV)              # Creating dataframe for
df.columns=['Player','Salary','Season']  #changing column name
df.head()
#df.count

            Player    Salary Season
0    Kent Bazemore  16910113   2018
1  Dennis Schroder  15500000   2018
2    Miles Plumlee  12500000   2018
3   Jamal Crawford  10942762   2018
4  Marco Belinelli   6606060   2018

In [4]:
#====================================================================================================
#==================Building Dataset for Current Players Ages with Player name as Key=================
#====================================================================================================

bball_age = os.path.join("Age_player.csv")

# Set empty list variables
Player= []
Age2018 = []

# Open current NBA CSV to zip important Values into a df
with open(bball_age, 'r') as csvFile:
   csvReader = csv.reader(csvFile, delimiter=',')

   # Skipp headers
   next(csvReader, None)

   for row in csvReader:

       # Append data from the row
       Player.append(row[0])
       Age2018.append(row[1])

       
# Zip lists together
AgeCSV = list(zip(Player, Age2018))
#AgeCSV

In [5]:
playerAge_df = pd.DataFrame(AgeCSV)
playerAge_df.columns=['Player','Age']  #changing column name
#playerAge_df.describe
playerAge_df.head()                    #Returns AGE vs Player name DF

            Player Age
0    Kent Bazemore  28
1  Dennis Schroder  24
2    Miles Plumlee  29
3   Dewayne Dedmon  28
4     Mike Muscala  26

In [6]:
drop_df= df.drop_duplicates(['Player', 'Season'])    # Needed to drop players with duplicate salaries forthe same season
df=drop_df

In [7]:
Group_ballers = df.groupby(['Player', 'Season'])['Salary']
#Group_ballers = df.groupby(['Season'])
Group_ballers
# Push the remade DataFrame to a new CSV file
#Group_ballers.to_csv("NBA_clean.csv", encoding="utf-8", index=False, header=True)

In [8]:
#====================================================================================================
#====================Pivot Table used to view dataset================================================
#=====================Not Needed, but I wanted to look at the dataset================================
#====================================================================================================

pivot_df=df.pivot(index="Player", columns="Season", values="Salary")
pivot_df

Season,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Player,,,,,,,,,,,,,,,,,,
A.C. Green,2250000,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
A.J. Guyton,316969,465850,18748,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
A.J. Hammons,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,650000,1312611
A.J. Price,None,None,None,None,None,None,None,None,None,457588,762195,854389,885120,None,62552,None,None,None
Aaron Brooks,None,None,None,None,None,None,None,None,1045560,1118520,None,None,3250000,1027424,None,2000000,2700000,2116955
Aaron Craft,None,None,None,None,None,None,None,None,None,None,None,None,None,None,35000,None,None,None
Aaron Gordon,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3992040,4171680,4351320,5504420
Aaron Gray,None,None,None,None,None,None,None,427163,711517,1000497,1028840,2500000,2575000,2690875,1227985,452059,452059,452059
Aaron Harrison,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,525093,375579,None
Aaron McKie,None,4000000,None,None,5500000,2500000,2500000,750000,None,None,None,None,None,None,None,None,None,None
Aaron Miles,None,None,None,None,None,155614,None,None,None,None,None,None,None,None,None,None,None,None
Aaron Williams,2250000,2475000,2700000,2925000,3790257,3375000,1750000,1890000,None,None,None,None,None,None,None,None,None,None
Abdel Nader,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1167333
Acie Law,None,None,None,None,None,None,None,1927080,2071680,2216160,656030,None,None,None,None,None,None,None
Adam Harrington,None,None,140636,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Adam Keefe,3390000,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Adam Morrison,None,None,None,None,None,None,None,None,4159200,5257229,None,None,None,None,None,None,None,None
Adonal Foyle,3580000,4400000,4400000,4400000,6500000,7312500,8125000,8937500,1262275,1306455,None,None,None,None,None,None,None,None
Adonis Thomas,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,60000,None,None
Adreian Payne,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1855320,1938840,2022240,None
Adrian Griffin,498500,565850,637435,751179,None,768718,1475000,1593000,1711000,None,None,None,None,None,None,None,None,None
Akil Mitchell,None,None,None,None,None,None,None,None,None,None,None,None,None,None,150000,None,None,None
Al Harrington,797880,1436982,5060000,5692500,6325000,6957500,7625000,8425625,9226250,10026875,5765000,6226200,6687400,3574300,3805000,None,None,None
Al Horford,None,None,None,None,None,None,None,3745800,4026720,4307640,5444857,12000000,12000000,12000000,12000000,12000000,26540100,27734405
Al Jefferson,None,None,None,None,1407240,1512840,None,2480885,11000000,12000000,13000000,14000000,15000000,None,None,13833333,10230179,9769821
Al Thornton,None,None,None,None,None,None,None,1652280,1776240,1900200,2814196,None,None,None,None,None,None,None
Al-Farouq Aminu,None,None,None,None,None,None,None,None,None,None,2563320,2755560,2947800,3700000,981084,7500000,7680965,7319035
Alan Anderson,None,None,None,None,None,None,None,None,None,None,None,None,885120,947907,1276061,4000000,1315448,None
Alan Henderson,5910000,6500312,7091250,7682188,8273125,1138500,None,None,None,None,None,None,None,None,None,None,None,None
Alan Williams,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,114285,874636,6000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
William Avery,1286160,1375920,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
William Cunningham,498500,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Willie Cauley-Stein,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3398280,3551160,3704160
Willie Green,None,None,None,None,620046,None,2800000,None,3388000,3682000,3976000,1223166,1475106,1399507,1448490,None,None,None
Willie Reed,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,947276,1015696,1577230
Willie Warren,None,None,None,None,None,None,None,None,None,None,500000,None,None,None,None,None,None,None
Willy Hernangomez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1375000,1435750
Wilson Chandler,None,None,None,None,None,None,None,1091640,1173480,1255440,2130482,None,5930414,6344164,6757913,10500000,11200000,12016854
Xavier Henry,None,None,None,None,None,None,None,None,None,None,2020200,2171640,2323200,None,1082000,None,None,None
Xavier Munford,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,89588,None,None
Yakhouba Diawara,None,None,None,None,None,None,None,687456,None,945000,None,None,None,None,None,None,None,None
Yanick Moreira,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,50000,None
Yao Ming,None,None,None,4147560,4436880,5594906,12455000,None,15070550,16378325,17686100,None,None,None,None,None,None,None
Yaroslav Korolev,None,None,None,None,None,1704480,1832280,None,None,None,None,None,None,None,None,None,None,None
Yi Jianlian,None,None,None,None,None,None,None,2777760,2986080,3194400,4050499,827197,None,None,None,None,250000,None
Yogi Ferrell,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,239767,1312611
Yuta Tabuse,None,None,None,None,108066,None,None,None,None,None,None,None,None,None,None,None,None,None
Zach Auguste,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,60000,None
Zach Collins,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3057240
Zach LaVine,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2055840,2148360,2240880,3202217
Zach Randolph,None,1019280,1095720,1172160,1504272,10666667,12000000,13333333,14666667,16000000,17666666,15200000,16500000,17800000,16500000,9638555,10361445,12307692
Zan Tabak,1200000,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Zarko Cabarkapa,None,None,None,1221240,1312800,1404360,2157097,None,None,None,None,None,None,None,None,None,None,None
Zaza Pachulia,None,None,None,366931,620046,4000000,4000000,4000000,4000000,4750000,4251250,4750000,5248750,5200000,5200000,5200000,2898000,3477600
Zeljko Rebraca,None,3500000,3850000,4200000,2500000,3000000,3240000,None,None,None,None,None,None,None,None,None,None,None
Zendon Hamilton,316969,465850,None,None,807546,329138,None,None,None,None,None,None,None,None,None,None,None,None
Zhou Qi,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,815615
Zoran Dragic,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1962103,2050397,None,None
Zoran Planinic,None,None,None,980280,1053720,1127280,150000,None,None,None,None,None,None,None,None,None,None,None
Zydrunas Ilgauskas,10130000,11250000,12375000,13500000,14625000,8740000,9442697,10142156,10841615,11541074,None,None,None,None,None,None,None,None

In [10]:
#NOT NEEDED, BUT WANTED
#=====================================================================================================
unique = df["Season"].unique()                         # Just showing the number years in my raw data
unique
#=====================================================================================================

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003',
       '2002', '2001'], dtype=object)

In [11]:
Dwight= df.loc[df["Player"] == "Dwight Howard"]         # I want to check the salary of a player over all the years to verify that my merged dataframes are putting data in the correct location
Jarrett= df.loc[df["Player"] == "Jarrett Jack"]         # I want to check the salary of a player over all the years to verify that my merged dataframes are putting data in the correct location

In [12]:
#===========================================================================================================
#============================The Next few cells created the dataframes for the yearly salaries==============
#===========================================================================================================

In [36]:
df2018= df.loc[df["Season"] == "2018"]
df2018= df2018.iloc[:,[0,1]]
df2018.head()

            Player    Salary
0    Kent Bazemore  16910113
1  Dennis Schroder  15500000
2    Miles Plumlee  12500000
3   Jamal Crawford  10942762
4  Marco Belinelli   6606060

In [37]:
df2017= df.loc[df["Season"] == "2017"]
df2017= df2017.iloc[:,[0,1]]
#df2017.head()
#df2017.reset_index

In [38]:
df2016= df.loc[df["Season"] == "2016"]
df2016= df2016.iloc[:,[0,1]]

In [39]:
df2015= df.loc[df["Season"] == "2015"]
df2015= df2015.iloc[:,[0,1]]
#df2015.head()

In [40]:
#===========================2014===========================================
#===========================================================================
df2014= df.loc[df["Season"] == "2014"]
df2014= df2014.iloc[:,[0,1]]
df2014.head()

#===========================2013===========================================
#===========================================================================
df2013= df.loc[df["Season"] == "2013"]
df2013= df2013.iloc[:,[0,1]]
df2013.head()

#===========================2012===========================================
#===========================================================================
df2012= df.loc[df["Season"] == "2012"]
df2012= df2012.iloc[:,[0,1]]
df2012.head()

#===========================2011===========================================
#===========================================================================
df2011= df.loc[df["Season"] == "2011"]
df2011= df2011.iloc[:,[0,1]]
df2011.head()

#===========================2010===========================================
#===========================================================================
df2010= df.loc[df["Season"] == "2010"]
df2010= df2010.iloc[:,[0,1]]
df2010.head()

#===========================2009===========================================
#===========================================================================
df2009= df.loc[df["Season"] == "2009"]
df2009= df2009.iloc[:,[0,1]]
df2009.head()

#===========================2008===========================================
#===========================================================================
df2008= df.loc[df["Season"] == "2008"]
df2008= df2008.iloc[:,[0,1]]
df2008.head()

#===========================2007===========================================
#===========================================================================
df2007= df.loc[df["Season"] == "2007"]
df2007= df2007.iloc[:,[0,1]]
df2007.head()

#===========================2006===========================================
#===========================================================================
df2006= df.loc[df["Season"] == "2006"]
df2006= df2006.iloc[:,[0,1]]
df2006.head()

#===========================2005===========================================#
#===========================================================================
df2005= df.loc[df["Season"] == "2005"]
df2005= df2005.iloc[:,[0,1]]
df2005.head()

#===========================2004===========================================
#===========================================================================
df2004= df.loc[df["Season"] == "2004"]
df2004= df2004.iloc[:,[0,1]]
df2004.head()

#===========================2003===========================================
#===========================================================================
df2003= df.loc[df["Season"] == "2003"]
df2003= df2003.iloc[:,[0,1]]
df2003.head()

#===========================2002===========================================
#===========================================================================
df2002= df.loc[df["Season"] == "2002"]
df2002= df2002.iloc[:,[0,1]]
df2002.head()

#===========================2001===========================================
#===========================================================================
df2001= df.loc[df["Season"] == "2001"]
df2001= df2001.iloc[:,[0,1]]
df2001.head()

#===========================2000===========================================
#===========================================================================
df2000= df.loc[df["Season"] == "2000"]
df2000= df2000.iloc[:,[0,1]]
df2000.head()

#df2001.head()

Empty DataFrame
Columns: [Player, Salary]
Index: []

In [41]:
#=============================MERGING OF THE DATASETS JUST CREATED FOR SALARY VS YEARS===============
#====================================================================================================

Compiled_df = df2018.merge(df2017, how='left', left_on="Player", right_on='Player',suffixes=('_2018','_2017')).fillna(0)   #Left Merge Command. Left merges does not delete data
Compiled_df = Compiled_df.merge(df2016, how='left', left_on="Player", right_on='Player',suffixes=('','_2016')).fillna(0)   #Left Merge Command. Left merges does not delete data
Compiled_df = Compiled_df.merge(df2015, how='left', left_on="Player", right_on='Player',suffixes=('','_2015')).fillna(0)
Compiled_df = Compiled_df.merge(df2014, how='left', left_on="Player", right_on='Player',suffixes=('','_2014')).fillna(0)
Compiled_df = Compiled_df.merge(df2013, how='left', left_on="Player", right_on='Player',suffixes=('','_2013')).fillna(0)
Compiled_df = Compiled_df.merge(df2012, how='left', left_on="Player", right_on='Player',suffixes=('','_2012')).fillna(0)
Compiled_df = Compiled_df.merge(df2011, how='left', left_on="Player", right_on='Player',suffixes=('','_2011')).fillna(0)
Compiled_df = Compiled_df.merge(df2010, how='left', left_on="Player", right_on='Player',suffixes=('','_2010')).fillna(0)
Compiled_df = Compiled_df.merge(df2009, how='left', left_on="Player", right_on='Player',suffixes=('','_2009')).fillna(0)
Compiled_df = Compiled_df.merge(df2008, how='left', left_on="Player", right_on='Player',suffixes=('','_2008')).fillna(0)
Compiled_df = Compiled_df.merge(df2007, how='left', left_on="Player", right_on='Player',suffixes=('','_2007')).fillna(0)
Compiled_df = Compiled_df.merge(df2006, how='left', left_on="Player", right_on='Player',suffixes=('','_2006')).fillna(0)
Compiled_df = Compiled_df.merge(df2005, how='left', left_on="Player", right_on='Player',suffixes=('','_2005')).fillna(0)
Compiled_df = Compiled_df.merge(df2004, how='left', left_on="Player", right_on='Player',suffixes=('','_2004')).fillna(0)
Compiled_df = Compiled_df.merge(df2003, how='left', left_on="Player", right_on='Player',suffixes=('','_2003')).fillna(0)
Compiled_df = Compiled_df.merge(df2002, how='left', left_on="Player", right_on='Player',suffixes=('','_2002')).fillna(0)
Compiled_df = Compiled_df.merge(df2001, how='left', left_on="Player", right_on='Player',suffixes=('','_2001')).fillna(0)
Compiled_df = Compiled_df.merge(df2000, how='left', left_on="Player", right_on='Player',suffixes=('','_2000')).fillna(0)


new_col=['Player','2018', '2017', '2016', '2015', '2014', '2013', '2012',
        '2011', '2010', '2009', '2008', '2007', '2006', '2005', 
        '2004', '2003', '2002', '2001', '2000']
                                 
Compiled_df.columns = new_col
#Compiled_df

In [42]:
#Compiled_df.to_csv("NBA_clean.csv", encoding="utf-8", index=False, header=True)
#Compiled_df.head()
#len(Compiled_df.index)

In [43]:
#====================================================================================================
#==================Creating final Dataframe with a Merge Function====================================
#=====Function conveniently deletes rows with index values that are not shared by both dataframes====
#====================================================================================================


Compiled_df = pd.merge(playerAge_df, Compiled_df, on="Player")
Compiled_df

,Player,Age,2018,2017,2016,2015,2014,2013,2012,2011,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Kent Bazemore,28,16910113,15730338,2000000,2000000,788872,473604,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Dennis Schroder,24,15500000,2708582,1763400,1690680,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Miles Plumlee,29,12500000,12500000,2109294,1169880,1121520,1073280,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Dewayne Dedmon,28,6000000,2898000,947278,816482,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Mike Muscala,26,5000000,1015696,947276,816482,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Malcolm Delaney,29,2500000,2500000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Taurean Waller-Prince,24,2422560,2318280,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,John Collins,20,1936920,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Isaiah Taylor,23,1312611,305000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Tyler Dorsey,22,815615,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Tyler Cavanaugh,24,50000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Tyler Cavanaugh,24,50000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,Jamal Crawford,38,10942762,13253012,5675000,5450000,5225000,5000000,5000000,10800000,...,0,7920000,0,6480000,5760000,2577937,2026680,1894560,1762320,0
13,Jamal Crawford,38,10942762,13253012,5675000,5450000,5225000,5000000,5000000,10800000,...,0,7920000,0,6480000,5760000,2577937,2026680,1894560,1762320,0
14,Marco Belinelli,32,6606060,6333333,6333333,2873750,2750000,1957000,3377604,2380270,...,0,1345800,0,0,0,0,0,0,0,0
15,Marco Belinelli,32,6606060,6333333,6333333,2873750,2750000,1957000,3377604,2380270,...,0,1345800,0,0,0,0,0,0,0,0
16,Ersan Ilyasova,30,6000000,8400000,7900000,7900000,7900000,7900000,2541000,2320500,...,0,0,664209,398762,0,0,0,0,0,0
17,Ersan Ilyasova,30,6000000,8400000,7900000,7900000,7900000,7900000,2541000,2320500,...,0,0,664209,398762,0,0,0,0,0,0
18,Richard Jefferson,37,2500000,2500000,1499000,1448490,11046000,10164000,9282000,8400000,...,13200000,12200000,11200000,10200000,2266794,1586280,1482840,1379400,0,0
19,Richard Jefferson,37,2500000,2500000,1499000,1448490,11046000,10164000,9282000,8400000,...,13200000,12200000,11200000,10200000,2266794,1586280,1482840,1379400,0,0
20,Mike Dunleavy,37,1662500,4837500,4500000,0,3183000,3750000,3750000,10561984,...,9000000,8219008,0,4506261,3565080,3332520,3100080,0,0,0
21,Okaro White,25,1312611,374933,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Okaro White,25,1312611,374933,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Sheldon Mac,25,1312611,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Diamond Stone,21,1312611,543471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Diamond Stone,21,1312611,543471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Nicolas Brussino,25,1312611,543471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Quinn Cook,25,100000,31969,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,Quinn Cook,25,100000,31969,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Jeremy Evans,30,50000,1227286,1100602,1794871,1660257,1794872,762195,473604,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Justin Hamilton,27,1000000,3000000,0,816482,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,K.J. McDaniels,25,100000,3333333,3333333,507336,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,Rudy Gobert,25,21974719,2121288,1175880,1127400,1078800,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,Ricky Rubio,27,14275000,13550000,12365000,5070686,4002120,3741120,3480120,0,...,0,0,0,0,0,0,0,0,0,0
500,Joe Ingles,30,14136364,2250000,2250000,507336,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
501,Derrick Favors,26,12000000,11050000,11933333,12833333,6008196,4753320,4443360,4133280,...,0,0,0,0,0,0,0,0,0,0
502,Alec Burks,26,10845506,10154495,9213484,3034356,2202000,2171640,2020200,0,...,0,0,0,0,0,0,0,0,0,0
503,Jae Crowder,27,6796117,6286408,6000000,915243,788872,600491,0,0,...,0,0,0,0,0,0,0,0,0,0
504,Thabo Sefolosha,33,5250000,3850000,4000000,4150000,3900000,3600000,3300000,3250000,...,1931160,1805160,1679280,0,0,0,0,0,0,0
505,Dante Exum,22,4992385,3940320,3777720,3615000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506,Jonas Jerebko,31,4000000,5000000,5000000,4500000,4500000,0,4500000,0,...,0,0,0,0,0,0,0,0,0,0
507,Ekpe Udoh,30,3200000,0,0,981084,4469548,3524880,3294960,3065040,...,0,0,0,0,0,0,0,0,0,0
508,Donovan Mitchell,21,2621280,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
509,Raul Neto,25,1471382,937800,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
510,Tony Bradley,20,1414920,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
511,Derrick Rose,29,2116955,21323250,20093063,0,17632688,16402500,6993708,5546160,...,4822800,0,0,0,0,0,0,0,0,0
512,Otto Porter,24,24773250,5893981,4662960,4470480,4278000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
513,Bradley Beal,24,23775506,22116750,5694674,4505280,4319280,4133280,0,0,...,0,0,0,0,0,0,0,0,0,0
514,John Wall,27,18063850,16957900,15851950,14746000,7459925,5915880,5530080,5144280,...,0,0,0,0,0,0,0,0,0,0
515,Ian Mahinmi,31,16661641,15944154,4000000,4000000,4000000,4000000,0,762196,...,1009200,938760,0,0,0,0,0,0,0,0
516,Marcin Gortat,34,12782609,12000000,11217391,10434782,7727280,7258960,6790640,0,...,711517,427163,0,0,0,0,0,0,0,0
517,Markieff Morris,28,8000000,7400000,8000000,2989239,2091840,2063040,1919160,0,...,0,0,0,0,0,0,0,0,0,0
518,Jason Smith,32,5225000,5000000,4300000,3278000,2500000,2500000,2500000,2187913,...,1326360,0,0,0,0,0,0,0,0,0
519,Jodie Meeks,30,3290000,6540000,6270000,6000000,1550000,1500000,854389,762195,...,0,0,0,0,0,0,0,0,0,0
520,Tomas Satoransky,26,3000000,2870813,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
521,Kelly Oubre,22,2093040,2006640,1920240,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
522,Tim Frazier,27,2000000,2090000,144157,59686,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
523,Mike Scott,29,1709538,3333334,3333333,3333333,788872,473604,0,0,...,0,0,0,0,0,0,0,0,0,0
524,Chris McCullough,23,1471382,1191480,1140240,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
525,Martell Webster,31,830000,830000,5613500,5381750,5150000,600000,5256000,4800000,...,3771133,2974080,2780160,2586120,0,0,0,0,0,0

In [26]:
drop2_df= Compiled_df.drop_duplicates(['Player', 'Age']) # Needed to drop players with duplicate salaries forthe same season

In [27]:
Compiled_df=drop2_df                                      #Moving final dataframe into global function

In [28]:
# Push the remade DataFrame to a new CSV file
Compiled_df.to_csv("NBA_clean.csv", encoding="utf-8", index=False, header=True)
len(Compiled_df.index)

492

In [ ]:
#END